### PR TITLE
Dev mode: simplified pom

### PR DESCRIPTION
**Pull request by evelinec**
- use the ideal(simplified) pom.xml 
- update the Readme content to use dev mode - N/A
  - keep the flow same (let discuss if the flow not work)
- convert `*Test` class to `*IT`
- convert to use JUnit 5 
  - use JUnit5 test order if need
- make sure to correctly configure the ports in test classes, server.xml, and pom.xml
- update travis test
   - `mvn install` cannot be used to verify anymore

### CODE REVIEW

**Comment by evelinec** [comment]
> Why need `test-compile`?

As stated in the pom and tested: 

`<!-- Since the package type is ear, need to run testCompile to compile the tests -->`

**Comment by NimG98** [comment]
### Adding dependencies between WAR and JAR modules

- [ ] maybe say `getFeet(cm)` "method". Or use another word that describes what `getFeet(cm)`/`getInches(cm)` are
    > The `getFeet(cm)` was added to the `setHeightFeet` method to convert a measurement into feet.

    > The `getInches(cm)` was added to the `setHeightInches` method to convert a measurement into inches.

### Assembling multiple modules into an EAR file

- [ ] Put a hotspot highlighting where the context root can be customized in the pom (e.g. highlight the line `<contextRoot>/converter</contextRoot>` in the pom, and use `contextRoot` as the hotspot word)
    > To customize the context root of the application, set the appropriate contextRoot in the webModule.

### Aggregating the entire build

- [ ] put file hotspots for mentions of the parent `pom.xml`

### Building the modules

- [ ] move the sentence "This command creates a JAR file in the jar/target directory, a WAR file in the war/target directory, and an EAR file in the ear/target directory, which contains the JAR and WAR files." to be in between the following 2 sentences
    > By aggregating the build in the previous section, you can run mvn install once from the start directory and it will automatically build all your modules. [INSERT SENTENCE HERE]. Use the following command to build the entire application from the start directory:

**Comment by NimG98** [comment]
Peer review (Nimrah):

- Linux (PENDING)
- Windows (PENDING)

**Comment by evelinec** [comment]
- maybe give description in this section of what to do when accessing http://localhost:9080/converter/ to see the application

=> Regarding the above comment, imo, the instruction on the web page after clicking the URL is self-explanatory: 

Height Converter
Enter the height in centimeters

Don't think it's necessary to add a description. Also the app is not the main focus of this guide.

**Comment by evelinec** [comment]
- on linux, the following predicted output of the command mvn liberty:start failsafe:integration-test liberty:stop is not shown at all:

=> About the above comment, I think you forgot to run the `mvn test-compile` after creating the test class. This step is required. You can check to see if the `target/test-classes/it/io/openliberty/guides/multimodules/IT.class` exist in your `ear` folder. If it doesn't exist, then no tests are run. @NimG98

**Comment by evelinec** [comment]
All other feedback are addressed in https://github.com/OpenLiberty/guide-maven-multimodules/pull/54/commits/4d8043a78bd57c488b431cf4179751240f86f90d.

**Comment by evelinec** [comment]
Verified changes on http://lgdev1.fyre.ibm.com:4060/guides/maven-multimodules.html. @NimG98 can you review?

**Comment by gkwan-ibm** [comment]
@evelinec 
- [ ] the artifact id for all should be `guide-maven-multimodules-xxx` instead of `guides-maven-multimodules-xxx`

**Pull request merged**
